### ISSUE TITLE
Storage Check-in / Check-out

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#178] opened 2023-03-01 19:56 UTC
- Will need a document, much like the Index master list, that describes the freezers and containers in detail so that we can model them in ESP first.

- This *might* be able to be accomplished via expressions or pipeline protocol will need to investigate.

**Comment by mcordes-gtac** [comment] 2023-03-10 18:14
Sent an email about this spreadsheet to @tim-snyder-wustl @LMT337 and Bill as well...

SeqLab has 3 total -20 freezers that we utilize for samples storage.  We have two smaller (identical) -20 freezers and a large -20 freezer.

Would it be possible to have location look like this on those worksheets that contain location based on 2D barcode ID.

Storage Location	Well
SeqLab1-1-1-rjXXX	A01

With Storage Location being Freezer-Shelf-Column-MatrixRack

I have attached a spreadsheet that I think shows what we will need for each of these.  Let me know if this makes sense or if you have any questions.

[SeqLab Freezer Organization 10March2023.xlsx](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/10944805/SeqLab.Freezer.Organization.10March2023.xlsx)

**Comment by LMT337** [comment] 2023-06-08 03:25
From the discussions we've had about storage, these are 'general' plans we were planning on implimenting.  We very much want to leverage the locations app and also tracking storage data on the Entities themselves.   Giving users more than one avenue to locate samples or sets of samples. 

2D Plate accessioning will have plate well locations provided by external collab, verified with visionmate.  Well locations are saved in worksheet and as Entity fields during ingest.  Plate creation could be a button or protocol action that would create a plate object, with Entities added to the corresponding well, Entity plate name field updated, Enity plate barcode field updated.  This would be instead of using the location column. 

Plate name generation would be similar to GTAC ID using hid_for_uui with a standardized naming format for each lab

Plate barcode needs to be printed during plate generation. 

Possible protocol columns that might be useful: 
column showing plate location in freezer/rack
location col with plate loaded, well location shown in field i.e the view a user would see if Plate selected in location column. Not necessary but would be nice to know how to do.  Entity well location is an Entity value so can be pulled in via ESP expression. 

Most lab processes creating new plates in workflows are either 1-1 or many-1.  This would also be virtual plate creation. 

Goal is to use well locations stored in Entity fields to avoid duplicate work assigning to wells in location app, at the same time create a plate with a unique name updated to Entity and worksheet, update plate barcode to the Entity and print plate barcodes.  We want to leverage plate Entities without have users create them manually in a Protocol. 

There may be more than one plate in a protocol, ingest will require them to have an unique name for plate creation. 

This will allow us to use the location app for storage and also allow tracking at the Entity level. 


Check In/Out task script:
User scan Entity BC (plate/tube etc..), scan check in location barcode.  Script adds Entity to location, updates Entity location fields with location. Should check Entity is not checked into other locations.  Check in multiple Entities at once?  

Check out does the same except it removes Enities from storage location and removes location from Entity field.  Checks that Entity has not already been checked out. Check out multiple Entities at once? 

We'd very much like to hit the ground running with this, SEQ and DNA will have the highest volume of storage requirements.  If we can get storage set up for SEQ, we can use that as a template for DNA and other labs.

**Comment by LMT337** [comment] 2023-08-02 14:38
Duplicate of #270 and #279

**Closed as completed** 2023-08-02 14:39 UTC
Labels: 🏷 ILP, 🏷 SC, 🏷 SEQ, :label: CLE
